

export default {
    INPUT_VALUE : 'CHANGE_INPUT_VALUE',
    ADD_TODO : 'ADD_TODO',
    DELETE_TODO : 'DELETE_TODO',
    CHECK_TODO : 'CHECK_TODO',
    CLEAR_COMPLETED: 'CLEAR_COMPLETED',
    CHANGE_VIEW: 'CHANGE_VIEW',
    CHANGE_ALL: 'CHANGE_ALL',
    ALTER_TEXT: 'ALTER_TEXT'
}
